### ISSUE TITLE
%s in translations

### ISSUE THREAD

**Issue by Harkann** [shrugal/PersoLootRoll#1]
I'm currently translating your addon in French and I need to change the order of some %s.
Is it possible for you to support this (by numbering these %s for example) ?

For exemple the correct translation for `Whispering is disabled, you need to ask %s1 for %s2 yourself -> %s3. ` is  `Le chuchotement est désactivé, vous devez demander %s2 à %s1 vous-même -> %s3`

**Comment by shrugal** [comment]
I feared that this might come up at some point. The bad news is that LUA's string:format function doesn't support reordering the arguments, but I think there are easy [workarounds](https://stackoverflow.com/a/20318955) for this, so I'll investigate them as soon as I have the time.

So yes, if there is no way around reordering the arguments then please do so, using #$ between the % and the s or d (so e.g. `%1$s` or `%3$d`). Of course I'll only be able to add those translations after the reordering feature is implemented.

Thanks for your translation efforts btw! 😃

**Comment by shrugal** [comment]
Ok never mind, implementing this was way easier than expected! It will be in the next version, so go ahead and reorder those translations however you like! One important thing is that you can't mix placeholder with  and without position, so "%s %s" and "%2$s %1$s" are both fine, but "%2$s %s" won't work.
